name: animated_theme_switcher
description: Flutter animated theme switcher, that help to create beautiful transactions during the theme switch.
version: 1.0.5
homepage: https://github.com/kherel/animated_theme_switcher

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: 1.9.0  

flutter:
  uses-material-design: true
